version: '2'
services:
    homerecipes-app:
        image: laloutre42/homerecipes
        external_links:
            - homerecipes-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/homerecipes?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    homerecipes-mysql:
        extends:
            file: mysql.yml
            service: homerecipes-mysql
